target: push
paths:
  remote: /home/institute/public/institute
  local: public
  static: [ ]
options: [ 'recursive' ]
env: "docsprod"
---
target: stage
paths:
  remote: /home/institute/staging/institute
  local: public
  static: [ ]
options: [ 'recursive' ]
env: "docsprod"
...
